#!/bin/bash

REALPATH=$(python -c "import os; print(os.path.realpath('$0'))")
BASE_DIR=$(dirname "${REALPATH}")
OUT_DIR="${BASE_DIR}/.cache/out"

function die() {
    echo "$1" >> /dev/stderr
    exit 1
}

if [[ "$OSTYPE" == darwin* ]]; then
    KINDLEGEN="${BASE_DIR}/KindleGen_Mac_i386_v2_9/kindlegen"
elif ! [ "${KINDLEGEN}" ]; then
    die "Unsupported OS, please provide path to kindlegen as KINDLEGEN"
fi

if ! [ -x "${KINDLEGEN}" ]; then
    die "No kindlegen found in ${BASE_DIR}!"
fi

python "${BASE_DIR}/ebookify.py" "$@" || die 'Failed to build HTML!'

BASE_NAME=$(basename "$1" '.json')

"${KINDLEGEN}" "${OUT_DIR}/${BASE_NAME}.opf"

if [ "$?" -gt 1 ]; then
    die 'Kindlegen failed!'
fi

mv "${OUT_DIR}/${BASE_NAME}.mobi" "${BASE_DIR}"
